### ISSUE TITLE
Not convert 0x302e31 bytes to uint

### ISSUE THREAD

**Issue by 26rahulsingh** [pipermerriam/ethereum-string-utils#5]
when i convert "0.1" string to bytes and then convert bytes to uint it's not converting. Is there any other way where i can convert "0.1" string to 0.1 uint value. plz help

**Comment by pipermerriam** [comment]
`0.1` cannot be represented as a `uint`... so I suspect that's the problem.

**Comment by 26rahulsingh** [comment]
Can you help me with to convert “0.1” string to byes and then to uint or to directly convert “0.1” string to uint.

On 02-Jun-2018, at 1:44 AM, Piper Merriam <notifications@github.com<mailto:notifications@github.com>> wrote:


0.1 cannot be represented as a uint... so I suspect that's the problem.

**Comment by pipermerriam** [comment]
You should try the ethereum stack exchange site.  It's a good place to get answers to questions like this.
